arc: add use of optimized versions of string functions for ARCv3 32-bit
foss-for-synopsys-dwc-arc-processors/uClibc pull request #8
Opened 2022-09-30 08:45 UTC by pavelvkozlov

Add ability to use optimized versions of string functions for ARCv3 32-bit CPUs with the UCLIBC_HAS_STRING_ARCH_OPT option. Add optimized **memcpy/memset/memcmp** for ARCv3 CPUs from the newlib and adapt for ARCv3 existed optimized for ARCv2 **strchr/strcmp/strcpy/strlen**.

Details:
**memset** and **memcpy**: implementations for the ```__ARC64_ARCH32__``` have been moved from the newlibc and conditional compilation for the ```__ARC_LL64__``` has been added.

**memcmp**:  has been adopted for ARCv3 32bit, copy chunks reduced form 32-byte to 16-byte; aggressive optimization that allows to read data for a next iteration in delay slots and read beyond the "count" has been  removed, as uclibc restricts such behavior and contains tests that check this.
```
nsim HS5x

timemembech with generic funcs
 standard memcpy                                      :     26.4 MB/s
 standard memset                                      :     86.4 MB/s

timemembech with optim funcs
 standard memcpy                                      :     95.0 MB/s
 standard memset                                      :    158.4 MB/s

cmptest 1Mb  with generic funcs
 strcmp time:    2.1 s
 memcmp time:    1.0 s
   
cmptest 1Mb with optim funcs
 strcmp time:    0.7 s
 memcmp time:    0.4 s

```

2022-09-30 09:01 UTC, shahab-vahedi commented
Great job @pavelvkozlov ! Specially for taking care of the correct amount of reads. In Linux we do care for that, but for baremetal (newlib) we are more relaxed. One question though: Are all the new codes tested for correct functionality?

2022-09-30 09:07 UTC, abrodkin requested changes

2022-09-30 09:07 UTC, abrodkin commented on libc/string/arc/memcpy.S
> + * Copyright (C) 2013-2022 Synopsys, Inc. (www.synopsys.com)
Copyright years must reflect only years when changes were really done. In that case it should be `2013, 2014-2015, 2017, 2022`.

2022-09-30 09:07 UTC, abrodkin commented on libc/string/arc/memset.S
> + * Copyright (C) 2013-2022 Synopsys, Inc. (www.synopsys.com)
Ditto

2022-09-30 09:07 UTC, abrodkin commented on libc/sysdeps/linux/arc/asm.h
> + * Some 16-bit instructions was excluded from the ARCv3 ISA
was -> were

2022-09-30 09:07 UTC, abrodkin commented on libc/sysdeps/linux/arc/asm.h
> + * the following macros are introduced to handle this changes in one place.
this -> these

2022-09-30 09:20 UTC, pavelvkozlov commented
> Are all the new codes tested for correct functionality?

I've ran all tests from standard uclibc-test pack. Test package contains a good set of tests for string functions.
```
Total skipped: 6
Total failed: 2
Total passed: 473
```
Also:
tinymembech, and my simple time measurement test.

2022-09-30 10:40 UTC, shahab-vahedi approved these changes

2022-09-30 12:16 UTC, abrodkin approved these changes

2022-10-07 07:32 UTC, pavelvkozlov commented
Thanks for the review. Then I'll prepare a patch and send it to the uclibc upstream.

2022-10-14 08:22 UTC, pavelvkozlov commented
The patch has been added to the uclibc-ng upstream: [commit](https://cgit.uclibc-ng.org/cgi/cgit/uclibc-ng.git/commit/?id=663b8a0497c40a20668258bd69db13924c569c41)

2022-10-14 08:22 UTC, closed without merging